### ISSUE TITLE
Lvl 2 Challenge 1: Pie chart task unclear

### ISSUE THREAD

**Issue by ArghyaBiswas0** [Open-Source-Community-VIT-AP/WSoC-TestRepo2#2]
The last task of Level 2 Challenge 1 says: 

`Build a pie chart displaying the percentage share of each subject.`

Not sure what the term "percentage share of each subject" signifies. Does this mean to plot out a pie chart of the percentage of students passed in each subject ?

Thanks for the help.

**Comment by SVijayB** [comment]
Yes, you need to plot a pie chart to show the percentage of students who have passed in **each** of the said subjects. 
So, for each of the subjects, you need to plot a different pie chart. If the number of students who have passed in a subject is 28, then the pass percentage is 56%. So plot the pie chart for **that** subject. Do the same for other subjects as well.

Sorry for the confusion. 

If this solves your query, please close the issue.

Thank you.

**Comment by ArghyaBiswas0** [comment]
Thanks for resolving the issue.
